name: proteusAI
channels:
  - pyg
  - pytorch
  - nvidia
  - conda-forge
  - anaconda
dependencies:
  - python=3.8
  # - pytorch-scatter
  - pytorch=2.4
  # - pyg
  # - cpuonly
  - pip
  - sphinx
  - pdbfixer
  - pip:
    - -e .[docs] -f https://data.pyg.org/whl/torch-2.4.0+cpu.html